"use strict";
const PUBLIC_CONTEXT=[{"title": "Istanbul lodging", "dates": "Sep 16–18", "city": "Istanbul", "summary": "Trip lodging context is preserved. Hotel name, address, contacts, confirmation and payment details are protected; use the single Secure Vault button at the top of the Hub when needed."}, {"title": "Cappadocia lodging", "dates": "Sep 18–21", "city": "Cappadocia", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Zagreb lodging", "dates": "Sep 21–23", "city": "Zagreb", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Plitvice lodging", "dates": "Sep 23–24", "city": "Plitvice Lakes", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Rovinj lodging", "dates": "Sep 24–27", "city": "Rovinj", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Ljubljana lodging", "dates": "Sep 27–30", "city": "Ljubljana", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Salzburg lodging", "dates": "Sep 30–Oct 2", "city": "Salzburg", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Zermatt lodging", "dates": "Oct 2–4", "city": "Zermatt", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Lucerne lodging", "dates": "Oct 4–5", "city": "Lucerne", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Zurich lodging", "dates": "Oct 5–6", "city": "Zurich", "summary": "Trip lodging context is preserved. Protected hotel details remain in Secure Vault."}, {"title": "Istanbul Airport lodging", "dates": "Oct 6–7", "city": "Istanbul Airport", "summary": "Return-positioning context is preserved. Protected hotel details remain in Secure Vault."}];
const mount=document.querySelector('[id$="Mount"], main .hotel-mount, main .transport-mount, main .cost-mount, main .day-mount')||document.querySelector('main');
function renderProtectedContext(){
  const host=document.getElementById('hotelMount')||document.querySelector('[id$="Mount"]'); if(!host)return; host.innerHTML='';
  PUBLIC_CONTEXT.forEach(c=>{const a=document.createElement('article');a.className='hotel-card';a.innerHTML=`<h2>${c.title}</h2><div class="meta"><span class="pill">${c.dates||''}</span><span class="pill">${c.city||''}</span></div><p>${c.summary}</p><p><strong>Protected details:</strong> traveler names, exact booking/confirmation data, addresses, contacts, payment notes, tickets, seats, and other Shared/Private fields are stored in Secure Vault and are not embedded in GitHub source.</p><p class="protected-location-note">Protected details are available from the single Secure Vault button at the top of the Hub.</p>`;host.appendChild(a);});
}
renderProtectedContext();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
