"use strict";
const PUBLIC_CONTEXT=[{"title": "Istanbul", "dates": "Sep 16–18", "city": "Istanbul", "summary": "General itinerary stop. Detailed lodging, transport and traveler records are protected."}, {"title": "Cappadocia", "dates": "Sep 18–21", "city": "Cappadocia", "summary": "General itinerary stop. Detailed activities and transfers are protected."}, {"title": "Zagreb / Plitvice / Rovinj", "dates": "Sep 21–27", "city": "Croatia", "summary": "General itinerary route. Detailed lodging and transfers are protected."}, {"title": "Ljubljana", "dates": "Sep 27–30", "city": "Ljubljana", "summary": "General itinerary stop. Detailed lodging and transfer records are protected."}, {"title": "Salzburg / Zermatt / Lucerne / Zurich", "dates": "Sep 30–Oct 6", "city": "Austria / Switzerland", "summary": "General extension route. Detailed hotel, rail and payment records are protected."}, {"title": "Return via Istanbul", "dates": "Oct 6–7", "city": "Istanbul / San Francisco", "summary": "General return route. Exact flight and lodging records are protected."}];
const mount=document.querySelector('[id$="Mount"], main .hotel-mount, main .transport-mount, main .cost-mount, main .day-mount')||document.querySelector('main');
function renderProtectedContext(){
  const host=document.getElementById('timelineMount')||document.querySelector('[id$="Mount"]'); if(!host)return; host.innerHTML='';
  PUBLIC_CONTEXT.forEach(c=>{const a=document.createElement('article');a.className='timeline-card';a.innerHTML=`<h2>${c.title}</h2><div class="meta"><span class="pill">${c.dates||''}</span><span class="pill">${c.city||''}</span></div><p>${c.summary}</p><p><strong>Protected details:</strong> traveler names, exact booking/confirmation data, addresses, contacts, payment notes, tickets, seats, and other Shared/Private fields are stored in Secure Vault and are not embedded in GitHub source.</p><p class="protected-location-note">Protected details are available from the single Secure Vault button at the top of the Hub.</p>`;host.appendChild(a);});
}
renderProtectedContext();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
