(() => {
  const HELP = {
    'help-center': {
      title: 'TEE Help Center', subtitle: 'Choose the section you are working in.',
      quick: `<div class="tee-help-cards"><button data-open-help="smart-intake"><strong>Smart Document Intake</strong><span>Analyze a source document, review classifications, and commit it to TEE.</span></button><button data-open-help="structured-documents"><strong>Structured Documents</strong><span>View, edit, verify, or delete documents already committed to TEE.</span></button><button data-open-help="source-manager"><strong>Source Document Manager</strong><span>Understand how retained original source files are classified and managed.</span></button></div>`,
      details: `<p>The Help Center collects the same contextual instructions available from each section's <strong>? How to use this</strong> button.</p><p>Use the section-specific help when you are unsure what a button does or what the next step should be.</p>`,
      security: `<p><strong>TEE access model:</strong> Public is open to everyone. Shared is protected and accessible to both traveling couples only. Private is protected and accessible only to the owning couple.</p><p>Uploading or importing protected records into TEE does not publish them to GitHub.</p>`,
      next: 'Choose the section you want help with.'
    },
    'smart-intake': {
      title: 'Smart Document Intake', subtitle: 'Turn a PDF/image into a reviewed TEE structured record.',
      quick: `<p><strong>Use the same six-step document workflow everywhere in TEE:</strong></p><ol><li><strong>Add source document.</strong> Select the original PDF/JPEG/PNG/WebP.</li><li><strong>Structure it.</strong> Analyze the source and load the proposed structured information into TEE.</li><li><strong>Review the structured result.</strong> Check extracted fields, Public / Shared / Private classifications, source sensitivity, category, and destination.</li><li><strong>Approve & Commit.</strong> This saves the approved structured information into TEE and creates/updates the usable record.</li><li><strong>Verify the destination record.</strong> Open the resulting Flights, Hotels, Rail, Identity, Insurance, or other destination and make sure the information is correct and usable.</li><li><strong>Archive the completed work item.</strong> When you are satisfied, archive it so it leaves the active work queue but remains available for reference.</li></ol><p><strong>Remember:</strong> Approve/Commit creates the usable TEE record. Archive means the document-processing job is finished; it is not deletion.</p>`,
      details: `<p><strong>Source document</strong> is the original PDF/image. <strong>Analysis JSON</strong> is only a temporary proposal; loading it does not yet save the record.</p><p>You may edit the title, category, original-document sensitivity, field labels, values, and classifications before committing.</p><p>Use <strong>Select all / Clear selection</strong> and the bulk Public / Shared / Private buttons when many items have the same access level.</p><p>If ChatGPT proposes a classification you disagree with, change it before commit. TEE treats your approved classification as final.</p>`,
      security: `<p>The original document should use the <strong>highest sensitivity present anywhere in the source</strong>.</p><p>Public fields may be displayed openly. Shared fields belong to both traveling couples only. Private fields belong only to the owning couple.</p><p>Do not classify booking references, ticket numbers, identity numbers, private payment information, or couple-specific personal information as Public.</p><p>The source file and protected fields remain device-local/protected; they are not added to the GitHub app package.</p>`,
      next: 'If a source is already selected, the next normal step is to load its ChatGPT analysis JSON.'
    },
    'structured-documents': {
      title: 'Structured Documents', subtitle: 'Manage records that have already been committed to TEE.',
      quick: `<p><strong>Structured Documents is steps 3–6 of the standard workflow:</strong></p><ol><li><strong>Review the structured result.</strong> Check the extracted information and classifications.</li><li><strong>Approve & Commit.</strong> Save the usable TEE record.</li><li><strong>Verify the destination record.</strong> Confirm the information appears correctly in the appropriate operational app.</li><li><strong>Archive when complete.</strong> Archive the finished work item so it leaves the active workspace but remains retrievable.</li></ol><p>Use <strong>Edit</strong> if anything needs correction. Use <strong>Needs Review</strong> to return a filed item to the work queue. Use <strong>Delete</strong> only when you truly want to remove the record.</p>`,
      details: `<p>A Structured Document is TEE's reconstructed operational version of a source document. It can contain Public, Shared, and Private fields/images within one coherent record.</p><p>The original source remains separate and uses the highest sensitivity needed by that source. The Structured Document can expose lower-sensitivity useful information without exposing the protected original.</p><p>Deleting a structured document removes the TEE record; it does not automatically delete a separately retained source file from your PC archive.</p>`,
      security: `<p>When the vault is locked, protected Shared/Private layers should not be readable. Unlocking the appropriate access level reveals only the information authorized for that user.</p><p>Private Couple A information must never be visible to Couple B, and vice versa. Shared is visible to both couples but is still protected from the public.</p>`,
      next: 'After Approve & Commit, verify the resulting destination record. If it is correct and complete, archive the finished work item.'
    },
    'source-manager': {
      title: 'Source Document Manager', subtitle: 'The control center for originals, processing history, and the source → structured record relationship.',
      quick: `<p><strong>Follow this exact six-step lifecycle:</strong></p><ol><li><strong>Add source document.</strong> Bring the original PDF/image into TEE.</li><li><strong>Structure it.</strong> Extract and organize the useful information.</li><li><strong>Review the structured result.</strong> Check fields, classifications, sensitivity, and destination.</li><li><strong>Approve / Commit.</strong> Create or update the usable TEE record.</li><li><strong>Verify the destination record.</strong> Make sure the result is correct in Flights, Hotels, Rail, Identity, Insurance, or the appropriate app.</li><li><strong>Archive the completed work item.</strong> Once satisfied, archive it so it leaves the active queue but remains available.</li></ol><p><strong>Needs Attention</strong> is your work queue. <strong>Structured</strong> shows completed-but-still-visible work. <strong>Archived</strong> is finished work retained for reference. <strong>All Sources</strong> shows the full history.</p>`,
      details: `<p><strong>What this section is for:</strong> It answers five questions: What original documents do I have? Which still need work? What did TEE create from each one? Where does the resulting information live? Where is the original if I need to verify it?</p><p><strong>Views:</strong> Needs Attention = active work queue; Structured = completed sources; Archived = retained but out of daily use; All Sources = full history.</p><p><strong>TEE created</strong> summarizes the structured document and extracted Public/Shared/Private items. Protected counts are intentionally hidden until the vault is unlocked.</p><p><strong>Original source status</strong> tells you whether TEE has an embedded local original, only a retained reference, or a missing source that needs attention.</p><p>The Source Document Manager does not replace Structured Documents. It manages the original and its processing history; Structured Documents manages the organized extraction; operational apps are where the trip information is used.</p>`,
      security: `<p>Never mark an original source Public until the entire file has been reviewed and contains no protected information.</p><p>Private sources require the owning couple. Shared sources are protected for both traveling couples. Public sources are open to everyone.</p>`,
      next: 'If an item is in Needs Attention, continue its six-step workflow. Archive only after the destination record has been verified.'
    }
  };

  const dialog = document.getElementById('teeHelpDialog');
  const title = document.getElementById('teeHelpTitle');
  const subtitle = document.getElementById('teeHelpSubtitle');
  const body = document.getElementById('teeHelpBody');
  const next = document.getElementById('teeHelpNext');
  let topic = 'help-center', tab = 'quick';
  function render(){ const h=HELP[topic]||HELP['help-center']; title.textContent=h.title; subtitle.textContent=h.subtitle; body.innerHTML=h[tab]; next.innerHTML=`<strong>What do I do next?</strong> ${h.next}`; document.querySelectorAll('.tee-help-tab').forEach(b=>b.classList.toggle('active',b.dataset.helpTab===tab)); }
  function open(t){ topic=t||'help-center'; tab='quick'; render(); if(typeof dialog.showModal==='function') dialog.showModal(); else dialog.setAttribute('open',''); }
  document.addEventListener('click',e=>{ const b=e.target.closest('[data-help-topic]'); if(b){open(b.dataset.helpTopic);return;} const o=e.target.closest('[data-open-help]'); if(o){topic=o.dataset.openHelp;tab='quick';render();return;} const t=e.target.closest('[data-help-tab]'); if(t){tab=t.dataset.helpTab;render();}});
  document.getElementById('teeHelpClose')?.addEventListener('click',()=>dialog.close());
  dialog?.addEventListener('click',e=>{ if(e.target===dialog) dialog.close(); });
})();
