"use strict";
const PUBLIC_CONTEXT=[{"title": "San Francisco → Istanbul", "dates": "Sep 15, 2026", "city": "San Francisco → Istanbul", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Istanbul", "dates": "Sep 16–18, 2026", "city": "Istanbul", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Cappadocia", "dates": "Sep 18–21, 2026", "city": "Cappadocia", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Zagreb", "dates": "Sep 21–23, 2026", "city": "Zagreb", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Plitvice Lakes", "dates": "Sep 23–24, 2026", "city": "Plitvice Lakes", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Rovinj / Pula", "dates": "Sep 24–27, 2026", "city": "Rovinj / Pula", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Ljubljana", "dates": "Sep 27–30, 2026", "city": "Ljubljana", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Salzburg", "dates": "Sep 30–Oct 2, 2026", "city": "Salzburg", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Zermatt", "dates": "Oct 2–4, 2026", "city": "Zermatt", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Lucerne", "dates": "Oct 4–5, 2026", "city": "Lucerne", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Zurich", "dates": "Oct 5–6, 2026", "city": "Zurich", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}, {"title": "Istanbul Airport / return", "dates": "Oct 6–7, 2026", "city": "Istanbul Airport / return", "summary": "Today/Tomorrow context remains public-safe. Open Secure Vault for exact hotel, transportation, booking, contact and traveler-specific details."}];
const mount=document.querySelector('[id$="Mount"], main .hotel-mount, main .transport-mount, main .cost-mount, main .day-mount')||document.querySelector('main');
function vaultHref(){return '../travel-private-documents/index.html';}
function renderProtectedContext(){
  const host=document.getElementById('dayMount')||document.querySelector('[id$="Mount"]'); if(!host)return; host.innerHTML='';
  PUBLIC_CONTEXT.forEach(c=>{const a=document.createElement('article');a.className='day-card';a.innerHTML=`<h2>${c.title}</h2><div class="meta"><span class="pill">${c.dates||''}</span><span class="pill">${c.city||''}</span></div><p>${c.summary}</p><p><strong>Protected details:</strong> traveler names, exact booking/confirmation data, addresses, contacts, payment notes, tickets, seats, and other Shared/Private fields are stored in Secure Vault and are not embedded in GitHub source.</p><div class="links"><a href="${vaultHref()}">Open Secure Vault</a></div>`;host.appendChild(a);});
}
renderProtectedContext();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
