"use strict";
const PUBLIC_CONTEXT=[
  {title:"Outbound international travel",dates:"Sep 15–16",days:["Sep 15","Sep 16"],city:"San Francisco → Istanbul",types:["Flight"],summary:"Confirmed in Turkish Airlines Manage Reservation: TK 80 departs SFO Sep. 15 at 18:45 and arrives IST Sep. 16 at 17:40. Traveler PNRs, ticket numbers and identity details remain protected in Secure Vault."},
  {title:"Istanbul arrival transfer",dates:"Sep 16",days:["Sep 16"],city:"Istanbul Airport → Istanbul",types:["Private transfer"],summary:"Private airport-to-hotel transfer is included in Part 1. Exact pickup instructions and contacts remain protected."},
  {title:"Istanbul → Cappadocia",dates:"Sep 18",days:["Sep 18"],city:"Istanbul → Kayseri / Cappadocia",types:["Flight","Private transfer"],summary:"Private hotel-to-airport transfer, domestic flight to Kayseri, then private onward transfer with an en-route Underground City visit."},
  {title:"Cappadocia → Zagreb",dates:"Sep 21",days:["Sep 21"],city:"Cappadocia → Kayseri → Istanbul → Zagreb",types:["Flight","Private transfer"],summary:"Private transfer to Kayseri airport, connecting flights via Istanbul, then private Zagreb airport transfer."},
  {title:"Zagreb → Plitvice Lakes",dates:"Sep 23",days:["Sep 23"],city:"Zagreb → Plitvice Lakes",types:["Private transfer"],summary:"Private road transfer to Plitvice Lakes, coordinated with the same-day national park visit."},
  {title:"Plitvice Lakes → Rovinj",dates:"Sep 24",days:["Sep 24"],city:"Plitvice Lakes → Rovinj",types:["Private transfer"],summary:"Private road transfer to Rovinj."},
  {title:"Rovinj → Ljubljana",dates:"Sep 27",days:["Sep 27"],city:"Rovinj → Postojna → Ljubljana",types:["Private transfer"],summary:"Private cross-border transfer with an en-route Postojna Cave visit."},
  {title:"Ljubljana → Salzburg",dates:"Sep 30",days:["Sep 30"],city:"Ljubljana → Villach → Salzburg",types:["Train"],summary:"Ljubljana 07:42 → Villach Hbf 09:22, INT 318; Villach Hbf 10:32 → Salzburg Hbf 12:53, IC 796. Keep the separately issued Villach→Salzburg reservation/ticket accessible."},
  {title:"Salzburg → Zermatt",dates:"Oct 2",days:["Oct 2"],city:"Salzburg → Zürich → Visp → Zermatt",types:["Train"],summary:"Salzburg Hbf 06:56 → Zürich HB 13:28, RJ 13478; Zürich HB 14:02 → Visp 16:04, IC 820; Visp 16:37 → Zermatt 17:50, RE 351. Carry the four original Salzburg→Zürich paper reservations."},
  {title:"Zermatt → Lucerne",dates:"Oct 4",days:["Oct 4"],city:"Zermatt → Visp → Bern → Lucerne",types:["Train"],summary:"Zermatt 08:37 → Visp 09:47, RE 226; Visp 10:54 → Bern 11:53, IC 817; Bern 12:36 → Luzern 14:03, RE 4371."},
  {title:"Lucerne → Zurich",dates:"Oct 5",days:["Oct 5"],city:"Lucerne → Zurich",types:["Train"],summary:"Luzern 09:09 → Zürich HB 09:51, TRN 2616. Direct train."},
  {title:"Zurich HB → Zurich Airport",dates:"Oct 6",days:["Oct 6"],city:"Zürich HB → Zürich Flughafen",types:["Train"],summary:"Zürich HB 10:02 → Zürich Flughafen 10:11, IC 513. Direct airport train."},
  {title:"Zurich → Istanbul Airport",dates:"Oct 6",days:["Oct 6"],city:"Zurich → Istanbul",types:["Flight"],summary:"TK 1208, ZRH 13:35 → IST 17:35. At Zurich check-in, verify the printed baggage tag destination before leaving the counter."},
  {title:"Istanbul → San Francisco",dates:"Oct 7",days:["Oct 7"],city:"Istanbul → San Francisco",types:["Flight"],summary:"TK 79, IST 13:15 → SFO 16:40. Traveler booking and ticket records remain protected in Secure Vault."}
];
const searchInput=document.getElementById('searchInput');
const typeFilter=document.getElementById('typeFilter');
const dateFilter=document.getElementById('dateFilter');
const resetBtn=document.getElementById('resetBtn');
const unique=v=>[...new Set(v)].filter(Boolean);
const RAIL_DAY_IDS={"Sep 30":"rail-sep30","Oct 2":"rail-oct2","Oct 4":"rail-oct4","Oct 5":"rail-oct5","Oct 6":"rail-oct6"};
function addOptions(select,values){if(!select)return;values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v+' · 2026';select.appendChild(o);});}
function movementDays(){const order=["Sep 15","Sep 16","Sep 18","Sep 21","Sep 23","Sep 24","Sep 27","Sep 30","Oct 2","Oct 4","Oct 5","Oct 6","Oct 7"];return order.filter(day=>PUBLIC_CONTEXT.some(c=>(c.days||[]).includes(day)));}
addOptions(typeFilter,unique(PUBLIC_CONTEXT.flatMap(c=>c.types||[])));
addOptions(dateFilter,movementDays());
if(dateFilter?.options?.[0])dateFilter.options[0].textContent='Choose travel date';
function visible(c){const q=(searchInput?.value||'').trim().toLowerCase();const type=typeFilter?.value||'all';const date=dateFilter?.value||'all';const blob=[c.title,c.dates,c.city,c.summary,...(c.types||[])].join(' ').toLowerCase();return(!q||blob.includes(q))&&(type==='all'||(c.types||[]).includes(type))&&(date==='all'||(c.days||[]).includes(date));}
function injectFocusStyles(){if(document.getElementById('transportFocus3527Styles'))return;const s=document.createElement('style');s.id='transportFocus3527Styles';s.textContent=`
  .toolbar{align-items:start}.toolbar #dateFilter{font-weight:850;background:#fff}.transport-day-glance{margin:0 0 16px}.transport-day-glance[hidden]{display:none}.day-glance-shell{background:#eef7fa;border:2px solid #8db8c8;border-radius:18px;padding:14px;box-shadow:0 3px 14px rgba(0,0,0,.06)}
  .day-glance-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.day-glance-kicker{font-size:.73rem;font-weight:900;letter-spacing:.09em;text-transform:uppercase;color:#526d78}.day-glance-shell h2{margin:.18rem 0 .25rem;color:#17384f;font-size:1.35rem}.day-glance-sub{margin:0;color:#51656e;font-size:.9rem}.day-glance-item{background:#fff;border:1px solid #cfe1e8;border-radius:13px;padding:11px;margin:8px 0}.day-glance-item h3{margin:0 0 3px;color:#17384f;font-size:1rem}.day-glance-route{font-weight:800;margin:0 0 4px}.day-glance-item p{margin:.25rem 0;line-height:1.38}.day-glance-types{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.day-glance-types span{background:#dce9ef;color:#17384f;border-radius:999px;padding:3px 8px;font-size:.74rem;font-weight:800}.day-glance-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.day-glance-actions button,.day-glance-actions a{border:0;text-decoration:none;border-radius:999px;padding:9px 11px;font:inherit;font-weight:850;background:#17384f;color:#fff;cursor:pointer}.day-glance-actions .secondary{background:#fff;color:#17384f;border:1px solid #aac9d4}
  .tee-date-focus main>.notice.private,.tee-date-focus main>.quick-grid,.tee-date-focus main>.movement-control,.tee-date-focus main>.operations-panel,.tee-date-focus main>.section-head,.tee-date-focus #protocolMount,.tee-date-focus footer{display:none!important}.tee-date-focus #transportMount{display:none}.tee-date-focus.tee-show-records #transportMount{display:grid}.tee-date-focus #teeRailReference{display:none}.tee-date-focus.tee-show-rail #teeRailReference{display:block}.tee-date-focus .transport-day-glance{margin-top:0}.tee-date-focus main{padding-top:12px}
  .transport-more-tools{margin:12px 0 18px}.transport-more-tools summary{cursor:pointer;font-weight:850;color:#17384f;padding:10px 12px;background:#fff;border:1px solid #d8e9ef;border-radius:12px}.transport-more-tools[open] summary{margin-bottom:10px}.transport-more-tools-body{display:grid;gap:8px;color:#53656d;font-size:.9rem}.transport-more-tools-body a{font-weight:800;color:#17384f}
  @media(max-width:760px){.day-glance-shell{padding:12px}.day-glance-top{display:block}.day-glance-actions{display:grid}.day-glance-actions button,.day-glance-actions a{text-align:center;min-height:44px}.toolbar{grid-template-columns:1fr}.toolbar #searchInput,.toolbar #typeFilter,.toolbar #resetBtn{display:none}.tee-date-focus .hero{padding-bottom:12px}.tee-date-focus .sub{display:none}}
`;document.head.appendChild(s);}
function ensureGlanceMount(){let host=document.getElementById('transportDayGlance');if(host)return host;host=document.createElement('section');host.id='transportDayGlance';host.className='transport-day-glance';const main=document.querySelector('main');const notice=main?.querySelector('.notice');if(notice)notice.insertAdjacentElement('afterend',host);else main?.prepend(host);return host;}
function ensureMoreTools(){let d=document.getElementById('transportMoreTools');if(d)return d;d=document.createElement('details');d.id='transportMoreTools';d.className='transport-more-tools';d.innerHTML=`<summary>Other transportation tools</summary><div class="transport-more-tools-body"><span>Search, transportation type filters, receipts, protocols and the full trip register remain available when no travel date is selected.</span><a href="#" data-clear-date>Show full Transportation app</a></div>`;ensureGlanceMount().insertAdjacentElement('afterend',d);d.querySelector('[data-clear-date]')?.addEventListener('click',e=>{e.preventDefault();if(dateFilter)dateFilter.value='all';document.body.classList.remove('tee-date-focus','tee-show-records','tee-show-rail');renderProtectedContext();window.scrollTo({top:0,behavior:'smooth'});});return d;}
function setDateFocus(date){const selected=date!=='all';document.body.classList.toggle('tee-date-focus',selected);if(!selected)document.body.classList.remove('tee-show-records','tee-show-rail');ensureMoreTools().hidden=!selected;window.dispatchEvent(new CustomEvent('tee-transport-date-changed',{detail:{date,open:false}}));}
function openRail(date){document.body.classList.add('tee-show-rail');window.dispatchEvent(new CustomEvent('tee-transport-date-changed',{detail:{date,open:true}}));requestAnimationFrame(()=>document.getElementById(RAIL_DAY_IDS[date])?.scrollIntoView({behavior:'smooth',block:'start'}));}
function renderDayGlance(){const host=ensureGlanceMount();const date=dateFilter?.value||'all';setDateFocus(date);if(date==='all'){host.hidden=true;host.innerHTML='';return;}const rows=PUBLIC_CONTEXT.filter(c=>(c.days||[]).includes(date));const railId=RAIL_DAY_IDS[date];host.hidden=false;host.innerHTML=`<div class="day-glance-shell"><div class="day-glance-top"><div><span class="day-glance-kicker">${date}, 2026 · TODAY'S TRANSPORTATION</span><h2>${rows.length?`${rows.length} movement${rows.length===1?'':'s'}`:'No scheduled transportation'}</h2><p class="day-glance-sub">Everything registered for this date is grouped here; the rest of Transportation stays out of the way.</p></div></div>${rows.length?rows.map(c=>`<article class="day-glance-item"><h3>${c.title}</h3><p class="day-glance-route">${c.city}</p><p>${c.summary}</p><div class="day-glance-types">${(c.types||[]).map(t=>`<span>${t}</span>`).join('')}</div></article>`).join(''):`<div class="day-glance-item">No transportation is currently registered for this date.</div>`}<div class="day-glance-actions">${railId?'<button type="button" data-open-rail>Full rail route & maps</button>':''}<button type="button" class="secondary" data-show-records>Detailed / secure records</button></div></div>`;host.querySelector('[data-open-rail]')?.addEventListener('click',()=>openRail(date));host.querySelector('[data-show-records]')?.addEventListener('click',()=>{document.body.classList.toggle('tee-show-records');const open=document.body.classList.contains('tee-show-records');host.querySelector('[data-show-records]').textContent=open?'Hide detailed / secure records':'Detailed / secure records';if(open)requestAnimationFrame(()=>document.getElementById('transportMount')?.scrollIntoView({behavior:'smooth',block:'start'}));});}
function renderProtectedContext(){injectFocusStyles();const host=document.getElementById('transportMount')||document.querySelector('[id$="Mount"]');if(!host)return;host.innerHTML='';const help=document.createElement('article');help.className='transport-card';help.innerHTML='<h2>Eurail rules / pass help</h2><p>Travel-day activation, live mobile tickets, seat reservations, paper/e-ticket handling and what to do when plans change.</p><p><a href="../travel-essentials/eurail-pass-help.html" style="font-weight:800">Open Eurail Pass Rules &amp; What To Do →</a></p>';host.appendChild(help);const rows=PUBLIC_CONTEXT.filter(visible);rows.forEach(c=>{const a=document.createElement('article');a.className='transport-card';a.innerHTML=`<h2>${c.title}</h2><div class="meta"><span class="pill">${c.dates||''}</span><span class="pill">${c.city||''}</span>${(c.types||[]).map(t=>`<span class="pill">${t}</span>`).join('')}</div><p>${c.summary}</p><p class="protected-location-note"><strong>Need seats, ticket/booking references or traveler-specific details?</strong> Unlock Secure Vault once, then use Vault Records.</p>`;host.appendChild(a);});if(!rows.length){const p=document.createElement('p');p.className='notice';p.textContent='No transportation matches the current filters.';host.appendChild(p);}renderDayGlance();}
searchInput?.addEventListener('input',renderProtectedContext);typeFilter?.addEventListener('input',renderProtectedContext);dateFilter?.addEventListener('change',()=>{if(searchInput)searchInput.value='';if(typeFilter)typeFilter.value='all';document.body.classList.remove('tee-show-records','tee-show-rail');renderProtectedContext();});resetBtn?.addEventListener('click',()=>{if(searchInput)searchInput.value='';if(typeFilter)typeFilter.value='all';if(dateFilter)dateFilter.value='all';renderProtectedContext();});
renderProtectedContext();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
