"use strict";
const PUBLIC_CONTEXT=[{"title": "Outbound international travel", "dates": "Sep 15–16", "city": "San Francisco → Istanbul", "summary": "International flight movement is part of the trip. Exact airline record, PNR, seats, ticket data and timing are protected in Secure Vault."}, {"title": "Turkey internal movement", "dates": "Sep 18–21", "city": "Istanbul / Cappadocia", "summary": "Flight and transfer details are protected in Secure Vault."}, {"title": "Croatia / Slovenia movement", "dates": "Sep 21–30", "city": "Zagreb → Plitvice → Rovinj → Ljubljana", "summary": "Transfer and rail/driver operational details are protected in Secure Vault."}, {"title": "Austria / Switzerland rail movement", "dates": "Sep 30–Oct 6", "city": "Ljubljana → Salzburg → Zermatt → Lucerne → Zurich", "summary": "Rail pass, reservation and exact train details are protected in Secure Vault."}, {"title": "Return international travel", "dates": "Oct 6–7", "city": "Zurich → Istanbul → San Francisco", "summary": "Exact flight, airport positioning, booking and seat details are protected in Secure Vault."}];
const mount=document.querySelector('[id$="Mount"], main .hotel-mount, main .transport-mount, main .cost-mount, main .day-mount')||document.querySelector('main');
function vaultHref(){return '../travel-private-documents/index.html';}
function renderProtectedContext(){
  const host=document.getElementById('transportMount')||document.querySelector('[id$="Mount"]'); if(!host)return; host.innerHTML='';
  PUBLIC_CONTEXT.forEach(c=>{const a=document.createElement('article');a.className='transport-card';a.innerHTML=`<h2>${c.title}</h2><div class="meta"><span class="pill">${c.dates||''}</span><span class="pill">${c.city||''}</span></div><p>${c.summary}</p><p><strong>Protected details:</strong> traveler names, exact booking/confirmation data, addresses, contacts, payment notes, tickets, seats, and other Shared/Private fields are stored in Secure Vault and are not embedded in GitHub source.</p><div class="links"><a href="${vaultHref()}">Open Secure Vault</a></div>`;host.appendChild(a);});
}
renderProtectedContext();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
